## 00. Pytorch Fundementals

In [1]:
#%pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
torch.__version__

'2.0.1+cu117'

In [4]:
#view statistics related to your GPU / TPU 
!nvidia-smi

Thu Jul 20 14:35:06 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.79                 Driver Version: 531.79       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070       WDDM | 00000000:04:00.0  On |                  N/A |
|  0%   47C    P3               37W / 240W|   3086MiB /  8192MiB |     28%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
torch.cuda.is_available()

True

## Introduction to Tensors
### Creating Tensors

In [6]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# get tensor back as a Python int
scalar.item()

7

In [9]:
#vector 
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [10]:
# MATRIX
matrix = torch.tensor([[7,8],[9,10]])
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [11]:
# Tensor
tensor = torch.tensor([[[[1,2,3],[4,5,6],[7,8,9]]]])
tensor

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [12]:
print(tensor.ndim)
print(tensor.shape)

4
torch.Size([1, 1, 3, 3])


### Random Tensors

In [16]:
# random tensors learn through random numbers and adjust these numbesr to
# better represent the data

tensor = torch.rand(3,4)
tensor


tensor([[0.2078, 0.7984, 0.8645, 0.2263],
        [0.5556, 0.2858, 0.7185, 0.4588],
        [0.2490, 0.4168, 0.3762, 0.4119]])

In [18]:
#create a random tensor similar to an image 
img_tensor = torch.rand(size=(3,224,224)) # C =(R,G,B), H, W 
img_tensor


tensor([[[0.7379, 0.2572, 0.4821,  ..., 0.8239, 0.7036, 0.8436],
         [0.3102, 0.2048, 0.9234,  ..., 0.8149, 0.9198, 0.0186],
         [0.9868, 0.6250, 0.1868,  ..., 0.0510, 0.3481, 0.8584],
         ...,
         [0.5702, 0.9757, 0.9508,  ..., 0.5932, 0.9689, 0.9054],
         [0.1444, 0.9834, 0.6900,  ..., 0.7842, 0.8847, 0.2266],
         [0.1418, 0.1955, 0.7037,  ..., 0.1496, 0.2356, 0.2207]],

        [[0.7680, 0.0845, 0.5195,  ..., 0.6505, 0.0978, 0.8636],
         [0.9636, 0.1540, 0.7675,  ..., 0.7202, 0.8372, 0.8607],
         [0.4244, 0.3812, 0.8218,  ..., 0.9611, 0.5950, 0.5671],
         ...,
         [0.5857, 0.3502, 0.1327,  ..., 0.8597, 0.4896, 0.8629],
         [0.4095, 0.3655, 0.9076,  ..., 0.3725, 0.9976, 0.2142],
         [0.0474, 0.2341, 0.6031,  ..., 0.3146, 0.3187, 0.3981]],

        [[0.6871, 0.9581, 0.8024,  ..., 0.3476, 0.9945, 0.9318],
         [0.5029, 0.8141, 0.3589,  ..., 0.5572, 0.7823, 0.5772],
         [0.9162, 0.2084, 0.9311,  ..., 0.3110, 0.9644, 0.

### Tensors of Zeroes and Ones

In [21]:
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
ones.dtype

torch.float32

### Tensors of Range

In [23]:
type1 = torch.arange(0,11,2) #start, stop, step
type1

tensor([ 0,  2,  4,  6,  8, 10])

In [24]:
# creating tensors like
one_to_ten = torch.arange(1,11,1)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])