## 00. Pytorch Fundementals

In [1]:
#%pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
torch.__version__

'2.0.1+cu117'

In [4]:
#view statistics related to your GPU / TPU 
!nvidia-smi

Fri Jul 21 16:23:53 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.79                 Driver Version: 531.79       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070       WDDM | 00000000:04:00.0  On |                  N/A |
|  0%   47C    P3               37W / 240W|   3750MiB /  8192MiB |     31%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
torch.cuda.is_available()

True

## Introduction to Tensors
### Creating Tensors

In [6]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# get tensor back as a Python int
scalar.item()

7

In [9]:
#vector 
vector = torch.tensor([7,7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [10]:
# MATRIX
matrix = torch.tensor([[7,8],[9,10]])
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [11]:
# Tensor
tensor = torch.tensor([[[[1,2,3],[4,5,6],[7,8,9]]]])
tensor

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [12]:
print(tensor.ndim)
print(tensor.shape)

4
torch.Size([1, 1, 3, 3])


### Random Tensors

In [13]:
# random tensors learn through random numbers and adjust these numbesr to
# better represent the data

tensor = torch.rand(3,4)
tensor


tensor([[0.0700, 0.9892, 0.5614, 0.7725],
        [0.0655, 0.6005, 0.8918, 0.7664],
        [1.0000, 0.6903, 0.2548, 0.7118]])

In [14]:
#create a random tensor similar to an image 
img_tensor = torch.rand(size=(3,224,224)) # C =(R,G,B), H, W 
img_tensor


tensor([[[0.4325, 0.3145, 0.1838,  ..., 0.1131, 0.2574, 0.8031],
         [0.0068, 0.2313, 0.8133,  ..., 0.0603, 0.9759, 0.2123],
         [0.5330, 0.0084, 0.7133,  ..., 0.4074, 0.0115, 0.8335],
         ...,
         [0.3625, 0.8178, 0.0772,  ..., 0.5000, 0.2458, 0.2206],
         [0.1241, 0.4000, 0.6908,  ..., 0.4939, 0.2882, 0.6531],
         [0.8609, 0.1052, 0.8910,  ..., 0.7967, 0.8925, 0.1772]],

        [[0.1124, 0.1630, 0.3912,  ..., 0.3373, 0.3401, 0.8807],
         [0.0477, 0.5885, 0.3936,  ..., 0.0109, 0.8787, 0.7866],
         [0.0193, 0.2534, 0.2602,  ..., 0.0218, 0.1267, 0.5399],
         ...,
         [0.7475, 0.7750, 0.0736,  ..., 0.6547, 0.5081, 0.2418],
         [0.5599, 0.9985, 0.8735,  ..., 0.4818, 0.2805, 0.9785],
         [0.6659, 0.1462, 0.2015,  ..., 0.1144, 0.6917, 0.8135]],

        [[0.4948, 0.0678, 0.3213,  ..., 0.8808, 0.6121, 0.0332],
         [0.4428, 0.6442, 0.9491,  ..., 0.8282, 0.0775, 0.4071],
         [0.9481, 0.8375, 0.5803,  ..., 0.7985, 0.8726, 0.

### Tensors of Zeroes and Ones

In [15]:
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
ones.dtype

torch.float32

### Tensors of Range

In [16]:
type1 = torch.arange(0,11,2) #start, stop, step
type1

tensor([ 0,  2,  4,  6,  8, 10])

In [17]:
# creating tensors like
one_to_ten = torch.arange(1,11,1)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
#### 3 Big Errors
- 1.) Tensors not the right datatype
- 2.) Tensors not the right shape
- 3.) Tensors not the right device

In [21]:
tensor = torch.tensor([3.0,6.0,9.0],
                      dtype=None, # datatype
                      device=None, # defaults to cpu => can go to cuda
                      requires_grad=False) # tracking gradients
tensor

tensor([3., 6., 9.])

In [19]:
# can use torch.float16
torch.tensor([3.0,6.0,9.0],dtype=torch.half,device='cuda',requires_grad=False)

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [24]:
tensor.type(torch.half)
tensor.dtype

torch.float32

# checking dtype
tensor.dtype
# checking shape
tensor.shape
# checking device
tensor.device


device(type='cpu')